spring:
  application:
    name: freshco-backend

  # ---------- DATABASE ----------
  datasource:
    url: jdbc:mysql://localhost:3306/freshco_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root1234

  # ---------- JPA ----------
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: admin

app:
  jwt:
    secret: 55ad4ecdcf21c3cf4e2eb7f2f80a52d6e24d068fec8198b25edeac32207e5e27
    expiration-milliseconds: 86400000

server:
  port: 8080